//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiremanSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident
    {
        public Accident()
        {
        }

        public Accident(string name, string date)
        {
            Name = name;
            Date = date;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
    }
}
