//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiremanSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiremanDBEntities2 : DbContext
    {
        public FiremanDBEntities2()
            : base("name=FiremanDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accidents> Accidents { get; set; }
        public virtual DbSet<Fireman> Fireman { get; set; }
        public virtual DbSet<Firetruck> Firetruck { get; set; }
        public virtual DbSet<AccidentsParticipants> AccidentsParticipants { get; set; }
    }
}
