//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiremanSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiremanDBEntities : DbContext
    {
        public FiremanDBEntities()
            : base("name=FiremanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accident> Accidents { get; set; }
        public virtual DbSet<Fireman> Firemen { get; set; }
        public virtual DbSet<Firetruck> Firetrucks { get; set; }
    }
}
